# AI 模型配置（必填）
DEEPSEEK_API_KEY = "tp-suggudkwp6wmdu7649j27c9h5edykg8k45kwnib9h9i1y9wu"
DEEPSEEK_BASE_URL = "https://token-plan-sgp.xiaomimimo.com/v1"
DEEPSEEK_MODEL = "mimo-v2.5-pro"

# 浏览器设置
BROWSER_HEADLESS = False
BROWSER_HUMANIZE = True
BROWSER_VIEWPORT = {"width": 1280, "height": 720}
BROWSER_LOCALE = "zh-CN"
BROWSER_TIMEZONE = "Asia/Shanghai"

# AI Agent 设置
MAX_ACTIONS_PER_STEP = 5
MAX_HISTORY_MESSAGES = 20
PAGE_LOAD_WAIT_MS = 3000
MAX_SNAPSHOT_ELEMENTS = 80
MAX_ELEMENT_TEXT_LENGTH = 60
ACTION_TIMEOUT_MS = 10000
MAX_ACTION_LOOP = 20
